apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devops-sample-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: sample.test
      http:
        paths:
          - path: /*
            backend:
              serviceName: devops-sample-service
              servicePort: 18080
