---
apiVersion: v1
kind: Service
metadata:
  name: devops-sample-service
spec:
  type: ClusterIP
  selector:
    app: devops-sample-service
  ports:
    - port: 18080
      targetPort: 18080
      protocol: TCP
